[package]
name = "bvyd"
version = "0.1.0"
authors = ["Terra Yi <terrayi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
youtube_dl = "0.6.0"
sanitize-filename = "0.3.0"
